version: "2"

services:

  jenkins:
    image: jenkins
    ports:
     - "8080:8080"
    volumes:
     - jenkins_data:/var/jenkins

  selenium-hub:
    image: selenium/hub
    ports:
      - "4444:4444"

  selenium-chrome-node:
    image: selenium/node-chrome
    environment:
      - HUB_PORT_4444_TCP_ADDR=selenium-hub
      - HUB_PORT_4444_TCP_PORT=4444

volumes:
  jenkins_data:
    external: true